security:
    encoders:
        App\Entity\App: bcrypt

    role_hierarchy:
        ROLE_CONSUMER: ROLE_USER
        ROLE_MANAGER: ROLE_CONSUMER

    providers:
        bilmo_storage:
            entity:
                class: App\Entity\App
                property: id

    firewalls:

        doc:
            pattern: ^(/(docs)?)$
            anonymous: true
            security: false

        login:
            pattern: ^/authentication
            stateless: true
            anonymous: true
            provider: bilmo_storage
            json_login:
                check_path: /authentication
                username_path: app_id
                password_path: app_secret
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                provider: bilmo_storage

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false