security:
    encoders:
        App\Entity\App: bcrypt

    providers:
        bilmo_storage:
            entity:
                class: App\Entity\App
                property: id

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # The docs is reachable via / and /docs
        # and security is disabled.
        # Up to me, this does not represent a security issue
        # insofar as Voters do their job perfectly.
        doc:
            pattern: ^(/(docs)?)$
            anonymous: true
            security: false

        # JSON Authentication with custom properties naming.
        login:
            pattern: ^/authentication
            stateless: true
            anonymous: true
            provider: bilmo_storage
            json_login:
                check_path: /authentication
                username_path: app_id
                password_path: app_secret
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            stateless: true
            anonymous: false
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                provider: bilmo_storage