# Doctrine extensions permits to focus on the main.
# Softdeletable is usefull to softdelete (and keeping relation)
# Timestampable keeps track of when the entity has been created/updated
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            softdeleteable: true
